// == CONVERSÃO IMPLICITA

// === CONVERSÃO EXPLICITA 

const numero = 5;
const texto = '5'

// COM ESSE TIPO DE COMPARAÇÃO ELE CONVERTE AS 2 VARIAVEIS PARA STRING E COMPARA O VALOR

// ELE SO COMPARA O VALOR !!!
console.log(numero == texto);


// COM ESSE TIPO DE COMPARAÇÃO ELE VERIFICA O TIPO DAS VARIAVEIS E DEPOIS O VALOR 
console.log(numero === texto);

// SEMPRE DEVEMOS FAZER A CONVERSÃO EXPLICITA NO TIPO DE VARIAVEL
Number()
String()